- name: Copy script to {{ groups['debian_cluster'] }}
  copy:
    src: "{{ inventory_dir }}/../mon"
    dest: ~/
    mode: "u=rx"

- name: Check response code
  command: "~/mon/main.sh"
  changed_when: false


