- name: Deploy monitoring to debian cluster
  hosts: debian_cluster
  remote_user: root
  
  any_errors_fatal: false
  gather_facts: no
  roles:
    - deploy_script
 # tasks:
 # - name: Set crontab on active nodes
 #   run_once: true
 #   delegate_to: "{{ item }}"
 #   cron:
 #     name: "Export df to xymon"
 #     minute: "*"
 #     job: "~/mon/main.sh"
 #   loop: "{{ ansible_play_batch }}"

